name: CI/CD Pipeline for GitHub Pages

on:
  push:
    branches:
      - main
      - '**/feature/*'
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

  merge:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate with GitHub CLI
      run: echo ${{ secrets.GH_PAT }} | gh auth login --with-token

    - name: Merge pull request
      run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

  deploy:
    needs: [build_and_test, merge]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_feature:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to GitHub Pages (feature branch)
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        publish_dir: ./build
        publish_branch: 'gh-pages-${{ github.ref_name }}'
