name: CI/CD Pipeline for GitHub Pages

on:
  push:
    branches:
      - main
      - '**/feature/*'
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and run tests
      run: |
        npm install
        npm test
        npm run build

  merge:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate with GitHub CLI
      run: echo ${{ secrets.GH_PAT }} | gh auth login --with-token

    - name: Merge pull request
      run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

  deploy:
    needs: [merge]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

    steps:
    - name: Set Git user identity
      run: |
         git config --global user.email "tefamora6@gmail.com"
         git config --global user.name "yachitzu"
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

  deploy_feature:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')


    steps:
    - name: Set Git user identity
      run: |
         git config --global user.email "tefamora6@gmail.com"
         git config --global user.name "yachitzu"
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set environment variables for deployment
      run: |
        echo "PUBLISH_DIR=./build" >> $GITHUB_ENV
        echo "PUBLISH_BRANCH=gh-pages-${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Deploy to GitHub Pages (feature branch)
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        PUBLISH_DIR: ./build
        PUBLISH_BRANCH: gh-pages-${{ github.ref_name }}
